// Flavor text. Per the plan: mystery in the surface, never in the mechanism —
// everything here is either purely decorative or, if it looks like a reading,
// is actually computed from something real.

export const BOOT_LINES = [
  'ASCIISYNTH SYS/7 — cold start',
  'checking core ................. OK',
  'checking lattice ............... OK',
  'checking filter bank 4/4 ....... OK',
  'checking west bus .............. OK',
  'checking carrier drift ......... FAULT (0x0F1)',
  'recalibrating carrier drift .... OK',
  'loading last patch ............. "(unnamed) recovered"',
  'routing matrix: 5 pins restored',
  '',
  'press any key to continue_',
];

export const HELP_LINES = [
  '§1  NAVIGATION',
  '    tab / shift-tab   cycle panel focus (east ▸ matrix ▸ west ▸ seq)',
  '    arrows            move within the focused panel',
  '    space             toggle matrix pin  ·  toggle seq step gate',
  '    + / -             nudge matrix pin depth · seq step pitch',
  '    i                 invert the focused matrix pin',
  '',
  '§2  VOICE',
  '    z x c v b n m , .   natural row, one octave from C',
  '    s d   g h j   l     sharps, positioned above the gaps',
  '    9 / 0               octave down / up',
  '',
  '§3  SEQUENCER  (tab to it, then:)',
  '    ← / →               select a step',
  '    ↑ / ↓               that step\'s pitch — shift for ±1 octave',
  '    space               toggle that step on/off',
  '    t                   toggle tie (holds the note into the next step)',
  '    r                   randomize all 16 steps (in the current scale)',
  '    enter               start / stop playback',
  '    [ / ]               tempo down / up (shift for ×5) — or :bpm <n>',
  '    the bright step is the one you\'re editing; the block cursor marks',
  '    what\'s playing — independent, edit ahead of the playhead freely',
  '',
  '§4  THE UNCERTAINTY SOURCE',
  '    [page torn]',
  '',
  '§5  COMMANDS',
  '    :save <name>       show the patch as text (copy it)',
  '    :load              paste a patch block back in',
  '    :patch <name>      drone · uncertainty · putney',
  '    :bpm <n>           set tempo (or [ / ] to nudge it)',
  '    :scale [name] [key]  set the sequencer\'s scale/key — re-snaps every',
  '                       step onto it. bare :scale lists scale names',
  '    :key <note>        change just the key (e.g. :key f#), re-snaps',
  '    :randseq [seed]    randomize the sequence (or press r on SEQ) —',
  '                       same seed, same sequence, every time',
  '    :rand [n]          scramble n random matrix pins only',
  '    :gen [seed]        generate a whole random patch — same seed,',
  '                       same patch, every time',
  '    :clear             clear the matrix',
  '    :panic             all notes off',
  '',
  '§6  MATRIX DESTINATION CODES',
  '    V1 VCO1.FM   V2 VCO2.FM   CX CPLX.INDEX  LC LADDER.CUTOFF',
  '    LI LADDER.IN FD FOLD.DRIVE FI FOLD.IN     LS LPG.STRIKE',
  '    VG VCA.GAIN  RC RING.CARRIER RI RING.IN     DT DELAY.TIME',
  '    PN PAN         ER ENTROPY.RATE            ML MASTER.LVL',
  '',
  '           esc to close · this page is not complete',
];

export const NOTES_LINES = [
  'west chain: normalled, unpatched',
  'filter self-osc threshold: .85',
  (epoch) => `signal integrity: ${(61 + Math.sin(epoch / 4000) * 6).toFixed(0)}%`,
  'patch memory: 3 slots free',
  'carrier drift — untraceable',
  'last visitor: —',
];
